Configure runtime upgrades via setCode call
Atleta-network/atleta-network-deploy pull request #7
Opened 2024-08-06 09:45 UTC by ales-tsurko

closes #4

2024-08-06 12:19 UTC, hrls approved these changes

2024-08-06 14:06 UTC, ales-tsurko commented on utils/set-code/index.js
> Node.js interactive session handles module files with `mjs` extension much better.

Sorry, I don’t understand what you mean. This PR introduces a single script with no modules. BTW it’s a draft and not ready for review yet 😄 @semeniak97mf is going to integrate it into deploy pipeline.

2024-08-06 15:44 UTC, hrls commented on utils/set-code/index.js
Oh, sorry, my bad.
Saw `"type": "module"` in `package.json`. I had some problems before using JS modules from REPL, like `.load <file>`. Actually, module extension in JS is `mjs`. Checked, it works both ways.

2024-08-06 16:55 UTC, ales-tsurko commented on utils/set-code/index.js
> Oh, sorry, my bad. Saw `"type": "module"` in `package.json`. I had some problems before using JS modules from REPL, like `.load <file>`. Actually, module extension in JS is `mjs`. Checked, it works both ways.

Oh, it's there to use the `import` (es-modules) syntax for modules instead of `require` (commonjs).

2024-08-07 15:11 UTC, hrls requested changes

2024-08-08 10:43 UTC, semeniak97mf commented on .github/workflows/upgrade-runtime-devnet.yml
> +        gh auth login --with-token <<< "${{ secrets.ACCESS_TOKEN }}"
Thanks, it's really more convenient this way. Corrected

2024-08-08 10:43 UTC, semeniak97mf commented on .github/workflows/upgrade-runtime-devnet.yml
> +        LATEST_RUNTIME=$(gh release list --repo Atleta-network/atleta --json tagName,createdAt --jq '.[] | select(.tagName | startswith("release-runtime-devnet")) | .tagName' | sort -r | head -n 1)
Okay, changed. Works

2024-08-08 10:45 UTC, semeniak97mf commented on .github/workflows/upgrade-runtime-devnet.yml
> +          npm install ./utils/set-code
Thanks, I forgot about this function with the declaration of the working directory.

2024-08-08 15:01 UTC, hrls approved these changes

2024-08-08 15:02 UTC, semeniak97mf approved these changes

2024-08-08 15:08 UTC, merged